### ISSUE TITLE
Add Metrics by URL

### ISSUE THREAD

**Issue by flaviostutz** [hairyhenderson/caddyprom#18] opened 2020-09-16 18:51 UTC
I really need metrics by URL in order to verify which endpoint is causing some bottlenecks and eventual problems. 

What do you think about implementing this on this project? I could work on this...

**Comment by hairyhenderson** [comment] 2020-09-17 18:16
Hi @flaviostutz, thanks for logging this issue.

I would highly discourage a general `"path"` labels in HTTP metrics. The problem is that especially in a general-purpose HTTP server like Caddy, URL paths are highly unbounded, and you _will_ end up with a cardinality explosion.

Outside of the context of Caddy, I usually label my HTTP metrics with a value equal to the pattern for that specific handler - so instead of having label values like `/v1/users/d5a5f5e3bc237453`, you get `/v1/users/{id}`, and hence you end up with well-bounded label cardinality.

So, I don't think #19 will be a good solution for this.

In addition, I've recently completed [a PR in the Caddy core](https://github.com/caddyserver/caddy/pull/3709) that add Prometheus metrics directly to Caddy. IMO it's far better than this module will ever be, and it does give you a `handler` label to help you better classify endpoints.

Unfortunately though at this point, the matchers system in Caddy makes it difficult to label HTTP metrics with the particular pattern that was matched, so there will be no way to label metrics by anything approximating the URL path _yet_. That's still an area that we're hoping to solve in the core Caddy metrics, in a way that doesn't break API and doesn't negatively affect performance.

I'm going to close this issue now, and the PR - thanks for putting the time into these, but I can't accept this feature right now.

**Closed as completed by hairyhenderson** 2020-09-17 18:16 UTC

**Comment by flaviostutz** [comment] 2020-09-18 02:15
I see the whole case in cardinality explosion. Currently I have a bunch of systems running and I would like to know which URLs are returning 500 or slowing down during crisis. I don't know how to monitor this. Your PR in Caddy core seems very promising!
